### ISSUE TITLE
task migration for nested checkboxes

### ISSUE THREAD

**Issue by rodrigoea** [rodrigoea/my-notion-journal#3]
In the task migration, only the first checkbox from a nested list is being moved to the current day's tasks. Subsequent checkboxes in the nested structure are not migrated.

**Comment by rodrigoea** [comment]
Thank you so much @InderParmar ☺️ 

Lmk if you have any questions, I created the issue very quickly this morning

**Comment by InderParmar** [comment]
Hi @rodrigoea , I am making progress on the issue and will soon submit a PR.

**Comment by rodrigoea** [comment]
hey hey @InderParmar -- no worries, thanks for your help!

**Comment by InderParmar** [comment]
Hi, @rodrigoea I have made the changes, can you review the PR, and if you are good with the PR, can you merge it by adding "hacktoberfest-accepted" label, as hacktoberfest is ending today. I will be very thankful.

**Comment by rodrigoea** [comment]
Hey @InderParmar -- it’s merged! 🎉

I also added the label 🙌🏻 Huge thanks for pitching in during Hacktoberfest and for your help here!
